server:
  port: 8005

spring:
  profiles:
    active: dev
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true


# to disable actuator endpoint security
management:
  security:
    enabled: false

security:
  basic:
    enable: false

zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    github:
       path: /github/**
       serviceId: github-api
    youtube:
          path: /youtube/**
          serviceId: youtube-api
    youtube-api-kotlin:
          path: /yk/**
          serviceId: youtube-api-kotlin

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 6000000